//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mogera.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mogera.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Select font languages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigureDisplayCultureButton_Text {
            get {
                return ResourceManager.GetString("ConfigureDisplayCultureButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CultureSelectDialogTitle_Text {
            get {
                return ResourceManager.GetString("CultureSelectDialogTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontSelectDialogTitle_Text {
            get {
                return ResourceManager.GetString("FontSelectDialogTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font size :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontSize_Text {
            get {
                return ResourceManager.GetString("FontSize_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font size must be 1 - 99. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontSizeRangeError_Text {
            get {
                return ResourceManager.GetString("FontSizeRangeError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample text :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SampleText_Text {
            get {
                return ResourceManager.GetString("SampleText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_Text {
            get {
                return ResourceManager.GetString("Search_Text", resourceCulture);
            }
        }
    }
}
